# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852fb072b183050bce97efc1e1e4db38c2cd86442eb5c046e8ac52bcd8a7cbde3ba6af87a984fee234425f97a2e84c15fb606497cab9a22aa59bcf74139a3f79

test:
  secret_key_base: 4185332910c1639613cc2b84754ac133f265ea5ea651600bfb8ea114a0e21b65b2c7e0b8982a37a0fc5f3726eff5556661ac65e8b1ad312c727722b1fc13d9ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
